### ISSUE TITLE
Never asks for root on magisk

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [dorumrr/privacyFlip#7]
Hi,

I'm using android 15 rooted via magisk but upon launching the app I notice that I'm never asked for root access. So the apps thinks I don't have root. Is there something that I'm not getting?

Just tested on 1.4.1

Thanks

**Comment by dorumrr** [comment]
Hey @thiswillbeyourgithub 

Please get [latest version](https://github.com/dorumrr/privacyFlip/releases) (currently v1.4.3) as it was not yet updated by FDroid to latest just yet. I do a lot of nightly builds. 

Let me know if you encounter same issue on latest. Uninstall first previous version to start clean.

**Comment by thiswillbeyourgithub** [comment]
Thanks. I uninstalled then added 1.4.3 via obtainium. Same situation.

**Comment by dorumrr** [comment]
Are you using `sui`? Under the hood, it uses `libsu` which is fully compatible with Magisk. I tested in thousand ways and I cannot replicate.

Can you check Superuser and see if app is there (but disabled) and also check your Deny list to see if it's checked there? Maybe enabling Zygisk will help, in case it's not already enabled.

As it seems to work in most cases, I suspect a misconfiguration on your device, but even if so, I would want to understand what is it so I can implement guards and have users warned when situations like these happen on their devices.

**Comment by AvengineeringCreates** [comment]
I had this issue on the stock ROM, running Android 13, that came with my phone but not with LineageOS 20 where it worked fine out-of-the-box. I can confirm that using `sui` worked for me in the case of the stock ROM. I do not know what the confounding variable is but hopefully this gives a clue.

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot;

I'm on linegeos.

Pkg list-installed shows:
`sudo/stable,now 1.2.0 all [installed]`

In the superuser tab the privacy flip is simply not there.

It is not in the deny list.

Zygisk is enabled.

Would you mind telling me which pkg you recommend me to install to fix this? And wether you think it might break things or not

**Comment by dorumrr** [comment]
I use [Andy Yan](https://sourceforge.net/projects/andyyan-gsi/files/)'s GSI: [lineage-21.0-20250621-UNOFFICIAL-arm64_bvN.img.gz](https://sourceforge.net/projects/andyyan-gsi/files/lineage-21-td/lineage-21.0-20250621-UNOFFICIAL-arm64_bvN.img.gz/download). I rooted the device with Magisk v29, enabled systemless host and zygisk.

**Comment by thiswillbeyourgithub** [comment]
I'm using the latest microg lineageos 22.2 ([link](https://download.lineage.microg.org/lynx/lineage-22.2-20251016-microG-NO-PI-PATCH-lynx.zip)), with the latest magisk (30.4), systemless host and zygisk.

I don't understand why this was closed?

**Comment by dorumrr** [comment]
> I don't understand why this was closed?

My bad! Apologies.

**Comment by dorumrr** [comment]
Hey @thiswillbeyourgithub 

I just [updated the app](https://github.com/dorumrr/privacyFlip/releases) (currently v2.0.0), maybe you want to give it a spin and see if it'll be picked up.

**Comment by thiswillbeyourgithub** [comment]
<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/f47565cc-a9f7-4f4f-a5b8-23781e3b3559" />

Nice UI but don't think it worked.

**Comment by dorumrr** [comment]
My difficulty lies in the fact that it seems to be a very isolated case, particular to your device config and it is very difficult for me to properly reproduce, test, and so on. Any suggestions from anyone who encounters or not same situation would be highly appreciated.

**Comment by thiswillbeyourgithub** [comment]
Alright, thank you very much.

If you are willing to create a debug release with a massive amount of logs enabled, I would be willing to give it a try and use logcat to gather the logs.

**Comment by veivataan** [comment]
I'm experiencing the same problem.
On oneplus nord 3, android 14, rooted with magisk.

**Comment by veivataan** [comment]
I forgot that i didn't delete the app and randomly (I don't remember interracting with the app) when I was in the home screen the request for root popped up. Weird. After that it worked like its supposed to but I deleted the app recently and now I am in the same situation as before.

**Comment by dorumrr** [comment]
@veivataan @thiswillbeyourgithub @AvengineeringCreates 

Please check out [v2.0.1](https://github.com/dorumrr/privacyFlip/releases/tag/v2.0.1) and hopefully the issues are now resolved.
Ideally remove any version you have on your device before installing the latest.

Thank you for your feedback!

**Comment by thiswillbeyourgithub** [comment]
Didn't fix it for me. I have yet to see a single root request for that app. Maybe it would be good to add a button that appears only if no root is detected that when clicked triggers the root detection code again and logs extensively what goes wrong?

**Comment by dorumrr** [comment]
@thiswillbeyourgithub @AvengineeringCreates @veivataan 

Hey guys,

I have been able to replicate the issue with permissions not being requested and implemented a fix. Check out [latest version](https://github.com/dorumrr/privacyFlip/releases) (currently v2.0.2) and let me know how it works out now. Make sure you remove previous version first just to ensure a clean slate.

**Comment by thiswillbeyourgithub** [comment]
That did it, thanks a lot!

**Comment by Reggie2561** [comment]
Same issue newst realease. Tried old realease doesn't work

**Comment by thiswillbeyourgithub** [comment]
The issue has not resurfaced in 2.0.9 for me but I haven't removed the root authorization so maybe I'm just not aware
